spring.datasource.url=jdbc:postgresql://localhost:5432/nmsci
spring.datasource.username=postgres

register-difficulty-target-nbits=0x20ffffff
transaction-difficulty-target-nbits=0x20ffffff

file-root-dir=temp
