spring.datasource.url=jdbc:postgresql://localhost:5432/nmsci
spring.datasource.username=postgres

nmsci.register-difficulty-target-nbits=0x20ffffff
nmsci.transaction-difficulty-target-nbits=0x20ffffff

nmsci.file-root-dir=temp
